### ISSUE TITLE
Question TableEntity input bindings

### ISSUE THREAD

**Issue by mmajcica** [marcduiker/azure-functions-university#22]
Is there an easy way to get all of the entities in a table or for a given partition?

On the Table attribute I do see the following constructor:

`public TableAttribute(string tableName, string partitionKey);`

and I was thinking that something like

`[Table("MyTable", "MyPartition")] MyPoco[] pocos`

could work, but it does not.

Any easy way to retrieve all of the items in a table or for a given partition, without using the CloudTable and executing a query?

Thanks

**Comment by marcduiker** [comment]
Hi @mmajcica,

Unfortunately not, the CloudTable is the only way to do this using an input binding. In Azure Functions runtime v1 you could also use an IQueryable<T> as input argument and read the entities from a partition but due to changes in the Storage SDK this is no longer possible in Azure Functions runtime v2 and v3. 

Also see [the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-input?tabs=csharp).

In general it's recommended to design your table so you can efficiently query it, even for large volumes of data.
More info on [table design for efficient querying](https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-design-for-query).
